#nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable cpt --yRange 0 5.3 --luminosity 3000 --binning 30 -2 2 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
#nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable cpQM --yRange 0 5.3 --luminosity 3000 --binning 30 -2 2 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &

#nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable ctZ --yRange 0 5.3 --luminosity 3000 --binning 30 -0.7 0.7 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
#nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable ctZI --yRange 0 5.3 --luminosity 3000 --binning 30 -0.7 0.7 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &

nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable c1V --yRange 0 5.3 --luminosity 3000 --binning 30 -0.4 0.6 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable c1A --yRange 0 5.3 --luminosity 3000 --binning 30 -0.65 0.55 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &

nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable c2V --yRange 0 5.3 --luminosity 3000 --binning 30 -0.06 0.06 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
nohup krenew -t -K 10 -- bash -c "python 1DNLLPlot.py  --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval_ac --variable c2A --yRange 0 5.3 --luminosity 3000 --binning 30 -0.06 0.06 --cores 2 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
